### ISSUE TITLE
[Question] Maintenance page

### ISSUE THREAD

**Issue by webmaxx** [manchenkoff/nuxt-auth-sanctum#130] opened 2024-07-25 10:40 UTC
Hi.
How can I implement a "maintenance" page?
When the page is updated, the "nuxt-auth-sanctum" plugin automatically sends a request to "endpoints.user". The answer comes with a 503 code, which I intercept with "interceptors".
But no matter what I do there, I go to the "login" page all the time. Even if the user was already logged in at that moment. I would like to display the "maintenance" page either at the current url or at a separate url.

```js
export default defineAppConfig({
    sanctum: {
        tokenStorage: localTokenStorage,
        interceptors: {
            onResponse: async (
                app: NuxtApp,
                ctx: FetchContext,
                logger: ConsolaInstance
            ) => {
                if (ctx.response?.status == 503) {
                    // Not work
                    navigateTo('/maintenance')

                    // It also doesn't work 
                    throw createError({ statusCode: 404, statusMessage: 'Unavailable' })
                }
            },
        },
    },
})
```

**Comment by manchenkoff** [comment] 2024-07-25 11:56
Hey @webmaxx, `onResponse` middleware provided by `ofetch` is not executed when it comes to errors, it has a different `onResponseError` interceptor but it is not exposed in my module.

So, in your scenario you want to redirect users to maintenance page whenever they get 503 response from the API, right?

My module redirects users only when it comes to 401 errors or when the `sanctum:auth` middleware is used on the target page (in case of 503 there is no user anymore). So, if you open a page that is not covered with `sanctum:auth` middleware you should not be redirected to login page even if you get 503 response. Is it correct that you are testing it on the page that uses `sanctum:auth` middleware?

**Comment by webmaxx** [comment] 2024-07-25 12:51
> Hey @webmaxx, `onResponse` middleware provided by `ofetch` is not executed when it comes to errors, it has a different `onResponseError` interceptor but it is not exposed in my module.

This condition is successfully fulfilled in the interceptor:
```js
if (ctx.response?.status == 503) {
    console.log('unavailable')
}
```


> So, in your scenario you want to redirect users to maintenance page whenever they get 503 response from the API, right?

Yes.

> My module redirects users only when it comes to 401 errors or when the `sanctum:auth` middleware is used on the target page (in case of 503 there is no user anymore). So, if you open a page that is not covered with `sanctum:auth` middleware you should not be redirected to login page even if you get 503 response. Is it correct that you are testing it on the page that uses `sanctum:auth` middleware?

I use globalMiddleware:
```js
sanctum: {
    ...
    globalMiddleware: {
        enabled: true,
    },
}
```

`pages/maintenance.vue`
```vue
<script setup lang="ts">
definePageMeta({
    sanctum: {
        excluded: true,
    }
})
</script>

<template>
    <div>
        Maintaince mode
    </div>
</template>
```

However, it is unclear why there is no user when responding with the code 503. A token is used for authorization, which is stored in the local storage. If maintenance mode is disabled on the server, then everything starts working again and the user exists.

```sh
php artisan up
```

**Comment by manchenkoff** [comment] 2024-07-25 14:19
> This condition is successfully fulfilled in the interceptor

Oh, that's good then. I'll see what changes you may need to do there.

> However, it is unclear why there is no user when responding with the code 503. A token is used for authorization, which is stored in the local storage. If maintenance mode is disabled on the server, then everything starts working again and the user exists.

Token in the storage doesn't mean that user exists until API returns a user as a response to identity endpoint, then the result is stored in user state (which is available as `useSanctumUser`). So the middleware uses that to determine if the redirect should be applied or not. The token itself might be expired or compromised, so we need a confirmation from the API.

I will try to reproduce the behavior you described to make sure that there are no bugs and I'll get back to you with either a solution or a bug-fix.

**Comment by webmaxx** [comment] 2024-07-25 14:36
Alternatively, can add a hook in which could define any actions before redirecting to the authorization page (for example, redefine the page for redirection, or immediately make a redirect). If don't use the hook, then everything will work by default.

**Comment by manchenkoff** [comment] 2024-07-25 21:03
So, I think I have a solution 😄 

Here is my maintenance page:

```typescript
<script setup lang="ts">
definePageMeta({
  sanctum: {
    excluded: true,
  },
})
</script>

<template>
  <div>
    Page: maintenance
  </div>
</template>

<style scoped></style>
```

Here is the sanctum config for the interceptors in `app.config.ts`:

```typescript
sanctum: {
  interceptors: {
    onRequest: async (
      app: NuxtApp,
      ctx: FetchContext,
      logger: ConsolaInstance,
    ) => {
      logger.debug(`custom onRequest interceptor (${ctx.request})`)
    },

    onResponse: async (
      app: NuxtApp,
      ctx: FetchContext,
      logger: ConsolaInstance,
    ) => {
      if (ctx.response?.status === 503) {
        // we use runWithContext to make sure that the operation will be done on the same Nuxt instance
        app.runWithContext(() => {
          const currentRoute = app.$router.currentRoute.value
          const maintenanceRoute = '/maintenance'

          if (currentRoute.path === maintenanceRoute) {
            return
          }

          navigateTo(maintenanceRoute)
        })
      }

      logger.debug(`custom onResponse interceptor (${ctx.request})`)
    },
  },
},
```

In my case, it worked well when the API was down. Please, try this one and let me know if it helps.

**Comment by manchenkoff** [comment] 2024-07-25 21:28
> Alternatively, can add a hook in which could define any actions before redirecting to the authorization page (for example, redefine the page for redirection, or immediately make a redirect). If don't use the hook, then everything will work by default.

The problem with hooks is that we will have to pass a lot of context there to make a proper decision and sometimes it's not related to the API response, making the module too complicated and easy to break with custom logic.

**Comment by webmaxx** [comment] 2024-07-26 08:53
Alas. There is only a transition to the "login" page. The "navigateTo(maintenanceRoute)" transition does not work.

```js
sanctum: {
    tokenStorage: localTokenStorage,
    interceptors: {
        onResponse: async (
            app: NuxtApp,
            ctx: FetchContext,
            logger: ConsolaInstance,
        ) => {
            console.log('log: 1')

            if (ctx.response?.status === 503) {
                console.log('log: 2')

                app.runWithContext(() => {
                    const currentRoute = app.$router.currentRoute.value
                    const maintenanceRoute = '/maintenance'

                    console.log('log: 3')

                    if (currentRoute.path === maintenanceRoute) {
                        console.log('log: 4')

                        return
                    }

                    console.log('log: 5')

                    navigateTo(maintenanceRoute)

                    console.log('log: 6')
                })
            }

            console.log('log: 7')
        },
    },
},
```

The following messages are displayed in the console:

```
GET http://api.sitename.lcl/api/me 503 (Service Unavailable)
log: 1
log: 2
log: 3
log: 5
log: 6
log: 7
nuxt-auth-sanctum:csr:error Unable to load user identity from API FetchError: [GET] "http://api.sitename.lcl/api/me": 503 Service Unavailable
```

**Comment by manchenkoff** [comment] 2024-07-26 09:41
Hey @webmaxx, could you try to use async approach?

```typescript
if (ctx.response?.status === 503) {
  // we use runWithContext to make sure that the operation will be done on the same Nuxt instance
  await app.runWithContext(async () => {
    const currentRoute = app.$router.currentRoute.value
    const maintenanceRoute = '/maintenance'

    if (currentRoute.path === maintenanceRoute) {
      return
    }

    await navigateTo(maintenanceRoute)
  })
}
```

**Comment by webmaxx** [comment] 2024-07-26 09:50
It didn't work. The result is the same.

**Comment by manchenkoff** [comment] 2024-07-26 09:55
@webmaxx okay, now this is weird 🤔 in my case both options work but I'm using [breeze-nuxt](https://github.com/manchenkoff/breeze-nuxt) application template, so maybe there is something additional that you have in your app that interferes with this behavior.

Since I can't reproduce the same, can you create a minimal repro to test on? or feel free to use breeze-nuxt as a starting point.

**Comment by webmaxx** [comment] 2024-07-26 10:43
Good. I will try to do this using the breeze-next template. I hope it works.
Thank you.

**Comment by manchenkoff** [comment] 2024-07-30 22:25
Hey @webmaxx, have you figured out the problem you had?

**Comment by webmaxx** [comment] 2024-08-01 07:42
Alas. Does not work. I will come back to this issue next week and check everything thoroughly.

**Comment by webmaxx** [comment] 2024-08-06 08:12
Unfortunately, it didn't work.
Redirects in interceptors are ignored.
If add a 503 error interception in the "composables/useApiError.ts" file and make a redirect, then this works if access the api. But if just refresh the page (for example, by pressing F5), then will be redirected to the login page, and not to the maintenance page.

**Comment by manchenkoff** [comment] 2024-08-06 11:11
Hey @webmaxx, I see. I will add this feature to breeze-nuxt to test it out again and get back to you in a couple of days.

**Comment by manchenkoff** [comment] 2024-08-07 23:52
Hey @webmaxx, the reason why your redirects didn't work is connected to this nuxt issue - https://github.com/nuxt/nuxt/issues/23698, but as a workaround I can suggest using `external` flag like this

```typescript
if (ctx.response?.status === 503) {
  app.runWithContext(async () => {
    const currentRoute = app.$router.currentRoute.value.path.replace(/\/$/, '')
    const maintenanceRoute = '/maintenance'

    if (currentRoute === maintenanceRoute) {
      return
    }

    await navigateTo(maintenanceRoute, { external: true })
  })
}
```

I also opened a PR with this implementation for breeze-nuxt, you can take a look before it is merged - https://github.com/manchenkoff/breeze-nuxt/pull/10

**Closed** 2024-08-08 16:47 UTC
Labels: question, investigate

**Comment by webmaxx** [comment] 2024-08-08 21:52
Stunningly. It's working. Thank you very much.
