### ISSUE TITLE
Issue with authenticating after sign-in

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [manchenkoff/nuxt-auth-sanctum#73] opened 2024-04-06 19:58 UTC
For some reason I cannot manage to successfully sign in.

I've read issue #34 however this one sadly did not lead to a solution for me.

When the package is accessing `/api/user` I get an unauthorized error.
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/1891578/eab3e472-27fa-49aa-9353-57e2067d7185)
![image](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/1891578/6218e210-96e1-44d2-8ef3-f826ff7b3767)

As visible in the images the cookies are made however there is no reason for the application to deny authorization. 

Does anyone have any idea on how to resolve this?

**Comment by manchenkoff** [comment] 2024-04-07 10:55
Hey @ILLuMiNaTe7, have you tried debugging your Laravel app to check why a user is not authenticated? I suggest checking `/login` response and comparing the XSRF header in the `/api/user` request to ensure they are the same.

Also, please consider filling out the **Bug** issue template since I already prepared a checklist of all information that might help to investigate the problem. You can either create a new issue or copy the content in the following comment from [here](https://github.com/manchenkoff/nuxt-auth-sanctum/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by ILLuMiNaTe7** [comment] 2024-04-07 15:53
@manchenkoff, I've adhered to your recommended format and raised a new issue. However, despite exploring the explanations provided, I haven't found a solution yet.

You can find the detailed report in issue #74.

One observation I made concerns the absence of `X-XSRF-TOKEN` in the `/api/user` request during login attempts. This might be a potential root cause of the issue.

**Comment by manchenkoff** [comment] 2024-04-07 17:50
Duplicate of #74

**Closed by manchenkoff** 2024-04-07 17:50 UTC
Labels: question, investigate
